FitTracker.Web2/Models/Applicant/ApplicantModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FitTracker.Web2.Models.Applicant
{
    public class ApplicantModel
    {
        public Int64 AppId { get; set; }

        public String Name { get; set; }

        public String ConsumerKey { get; set; }

        public String ConsumerSecret { get; set; }

        public String NotificationUrl { get; set; }
    }
}

FitTracker.Web2/Models/Applicant/IndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FitTracker.Web2.Models.Applicant
{
    public class IndexModel
    {
        public Int64 UserId { get; set; }

        public List<ApplicantModel> Applicants { get; set; }
    }
}

FitTracker.Web2/Models/Applicant/RegisterModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitTracker.Web2.Models.Applicant
{
    public class RegisterModel
    {
        public Int64 AppId { get; set; }

        [Required]
        public Int64 UserId { get; set; }

        [Required]
        [Display(Name = "App name")]
        public String AppName { get; set; }

        [Required]
        [Display(Name = "Notification Url")]
        public String NotificationUrl { get; set; }
    }
}

FitTracker.Web2/Controllers/ApplicantController.cs
using FitTracker.Data;
using FitTracker.Data.Entities.Auth;
using FitTracker.Data.Helpers;
using FitTracker.Data.Repo.Auth;
using FitTracker.Web2.Core;
using FitTracker.Web2.Models.Applicant;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitTracker.Web2.Controllers
{
    [Authorize]
    public class ApplicantController : BaseController
    {
        public ActionResult Index()
        {
            Int64 userId = AuthUser.UserId;

            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                IndexModel result = new IndexModel();

                var repoApplicant = uow.GetRepo<IApplicantRepo>();

                var applicants = repoApplicant.GetByUserId(userId).ToList();

                if (applicants == null) applicants = new List<Data.Entities.Auth.Applicant>();

                result.UserId = userId;
                result.Applicants = applicants
                    .Select(x => new ApplicantModel()
                    {
                        AppId = x.PkID,
                        Name = x.UniqueId,
                        ConsumerKey = x.ConsumerKey,
                        ConsumerSecret = x.ConsumerSecret,
                        NotificationUrl = x.NotificationUrl
                    })
                    .ToList();

                return View(result);
            }
        }

        [HttpGet]
        public ActionResult Register(Int64 userId)
        {
            RegisterModel model = new RegisterModel();
            model.UserId = userId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                using (var uow = UnityManager.Resolve<IUnitOfWork>())
                {
                    var repoApplicant = uow.GetRepo<IApplicantRepo>();

                    var app = new Applicant();

                    app.UniqueId = model.AppName;
                    app.UserId = model.UserId;
                    app.ConsumerKey = Crypto.DoConsumerKey();
                    app.ConsumerSecret = Crypto.DoConsumerSecret();
                    app.NotificationUrl = model.NotificationUrl;

                    repoApplicant.Save(app);

                    uow.Commit();

                    return RedirectToAction("Index", new { userId = model.UserId });
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Update(Int64 appId)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repoApplicant = uow.GetRepo<IApplicantRepo>();

                var app = repoApplicant.Get(appId);
                
                RegisterModel model = new RegisterModel();
                model.UserId = app.UserId;
                model.AppName = app.UniqueId;
                model.NotificationUrl = app.NotificationUrl;

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Update(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                using (var uow = UnityManager.Resolve<IUnitOfWork>())
                {
                    var repoApplicant = uow.GetRepo<IApplicantRepo>();

                    var app = repoApplicant.Get(model.AppId);

                    app.UniqueId = model.AppName;
                    app.NotificationUrl = model.NotificationUrl;

                    repoApplicant.Save(app);

                    uow.Commit();

                    return RedirectToAction("Index", new { userId = model.UserId });
                }
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult Delete(Int64 appId)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repoApplicant = uow.GetRepo<IApplicantRepo>();

                repoApplicant.Remove(appId);
                uow.Commit();

                return RedirectToAction("Index");
            }
        }
    }
}

FitTracker.Web2/Views/Applicant/Index.cshtml
@model FitTracker.Web2.Models.Applicant.IndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Applications</h2>

<div class="row">
    <a href="@Url.Action("Register", "Applicant", new {userId = Model.UserId})" class="btn btn-default">New App</a>
</div>

<div class="row">
    <table data-toggle="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Consumer Key</th>
            <th>Consumer Secret</th>
            <th>Notification Url</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Applicants)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.ConsumerKey</td>
                <td>@item.ConsumerSecret</td>
                <td>@item.NotificationUrl</td>
                <td>
                    <a href="/Applicant/Update?appId=@item.AppId">Edit</a>
                    &nbsp;|&nbsp;
                    <a href="/Applicant/Delete?appId=@item.AppId">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

FitTracker.Web2/Views/Applicant/Register.cshtml
@model FitTracker.Web2.Models.Applicant.RegisterModel

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a New App</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("Register", "Applicant", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true, "App creation was unsuccessful. Please correct the errors and try again.")
            <div>
                <fieldset>
                    <legend>App Information</legend>

                    @Html.HiddenFor(m => m.AppId)
                    @Html.HiddenFor(m => m.UserId)

                    <div class="form-group">
                        @Html.LabelFor(m => m.AppName, new {@class = "col-md-2 control-label"})
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.AppName, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.AppName, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.NotificationUrl, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.NotificationUrl, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NotificationUrl, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Register" class="btn btn-default" />
                        </div>
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

FitTracker.Web2/Views/Applicant/Update.cshtml
@model FitTracker.Web2.Models.Applicant.RegisterModel

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update App</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Update", "Applicant", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.ValidationSummary(true, "App update was unsuccessful. Please correct the errors and try again.")
    <div>
        <fieldset>
            <legend>App Information</legend>

            @Html.HiddenFor(m => m.AppId)
            @Html.HiddenFor(m => m.UserId)

            <div class="form-group">
                @Html.LabelFor(m => m.AppName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.AppName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.AppName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.NotificationUrl, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.NotificationUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.NotificationUrl, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}